environment:
  matrix:
    - nodejs_version: 8
      platform: x64
    - nodejs_version: 8
      platform: x86
    - nodejs_version: 10
      platform: x64
    - nodejs_version: 10
      platform: x86
    - nodejs_version: 12
      platform: x64
    - nodejs_version: 12
      platform: x86
    # electron
    - nodejs_version: 10
      platform: x64
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 8.1.1
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      platform: x86
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 8.1.1
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      platform: x64
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 7.1.14
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      platform: x86
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 7.1.14
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      platform: x64
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 6.1.9
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      platform: x86
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 6.1.9
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      platform: x64
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 5.0.6
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      platform: x86
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 5.0.6
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      platform: x64
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 4.2.6
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      platform: x86
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 4.2.6
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      platform: x64
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 3.1.11
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron
    - nodejs_version: 10
      platform: x86
      NODE_RUNTIME: electron
      NODE_RUNTIME_VERSION: 3.1.11
      TOOLSET_ARGS: --dist-url=https://atom.io/download/electron

os: Visual Studio 2015


install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy: OFF
